import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "aos/dist/aos.css";
import ClientWrapper from "../components/ClientWrapper";
import RouteLoader from "./../components/RouteLoader";
import { ActivitiesProvider } from "./../components/context/ActivitiesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bondi Patshala Foundation",
  description: "Generated by create next app",
  icons: {
    icon: "/bp-2.png", // This points to public/favicon.ico
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased !bg-white bg-no-repeat`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <ActivitiesProvider>
            <RouteLoader />

            <ClientWrapper>{children}</ClientWrapper>
          </ActivitiesProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
